# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 15:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('reviewer', models.CharField(blank=True, max_length=100, null=True)),
                ('review_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Unreviewed', 'Unreviewed'), ('Researching', 'Researching'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Unreviewed', max_length=20)),
                ('severity', models.CharField(choices=[('Low', 'LOW'), ('Medium', 'MEDIUM'), ('High', 'HIGH'), ('Critical', 'CRITICAL')], default='Low', max_length=10)),
            ],
            options={
                'ordering': ('-created_at',),
                'db_table': 'Alert',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=functools.partial(django.utils.timezone.localtime, *(datetime.datetime(2017, 10, 29, 15, 35, 3, 231517),), **{}), null=True)),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='event',
            field=models.ManyToManyField(blank=True, to='alerts.Event'),
        ),
    ]
