# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 08:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(default=functools.partial(django.utils.timezone.localtime, *(datetime.datetime(2017, 10, 27, 8, 55, 19, 556004, tzinfo=utc),), **{}), null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='review_time',
            field=models.DateTimeField(blank=True, default=functools.partial(django.utils.timezone.localtime, *(datetime.datetime(2017, 10, 27, 8, 55, 19, 556163, tzinfo=utc),), **{}), null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(default=functools.partial(django.utils.timezone.localtime, *(datetime.datetime(2017, 10, 27, 8, 55, 19, 563108, tzinfo=utc),), **{}), null=True),
        ),
    ]
