# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_ip', models.GenericIPAddressField()),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('last_login', models.DateTimeField(auto_now_add=True, null=True)),
                ('login_type', models.CharField(choices=[('normal', 'normal'), ('root', 'root')], default='normal', max_length=10)),
                ('failed_attempts', models.IntegerField(default=0)),
            ],
        ),
    ]
